import { Inter } from "next/font/google";
import "./globals.css";
import MenuLayout from "@/components/menu/MenuLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <MenuLayout />
                {children}
            </body>
        </html>
    );
}
