import { Inter } from "next/font/google";
import "./globals.css";
import FooterLayout from "@/components/footer/FooterLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={
                    (inter.className, "flex flex-col justify-between h-screen")
                }
            >
                {children}
                <FooterLayout />
            </body>
        </html>
    );
}
