import PlainMenu from "@/components/menu/PlainMenu";
import { Fragment } from "react";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function userLayout({ children }) {
    return (
        <Fragment>
            <PlainMenu />
            {children}
        </Fragment>
    );
}
